apiVersion: v2
name: ping-quarkus
version: 0.0.0
appVersion: 0.0.0
description: Ping quarkus
keywords:
  - ping quarkus
sources:
  - https://github.com/onecx/ping-quarkus
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.42.0
    repository: oci://ghcr.io/onecx/charts
